name: news_app_ui_setup
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.0
  cupertino_icons: ^1.0.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  hidden_drawer_menu: ^3.0.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  # Added for app icon management
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

# Add the flutter_icons section outside of the flutter section
flutter_icons:
  android: true
  ios: true
  image_path: "assets/1759492.png"  # Your icon path here
